import { shuffle } from "@/lib/utils";

export const themes = [
  { id: "animals", name: "Animais" },
  { id: "characters", name: "Personagens" },
  { id: "movies", name: "Filmes" },
  { id: "places", name: "Locais" },
  { id: "objects", name: "Objetos" },
  { id: "famous", name: "Famosos" }
] as const;

export type ThemeId = typeof themes[number]["id"];

export interface GuessItem {
  id: string;
  name: string;
  theme: ThemeId;
}

export const items: GuessItem[] = [
  // Animais
  { id: "lion", name: "Leão", theme: "animals" },
  { id: "elephant", name: "Elefante", theme: "animals" },
  { id: "giraffe", name: "Girafa", theme: "animals" },
  { id: "penguin", name: "Pinguim", theme: "animals" },
  { id: "dolphin", name: "Golfinho", theme: "animals" },
  { id: "monkey", name: "Macaco", theme: "animals" },
  { id: "tiger", name: "Tigre", theme: "animals" },
  { id: "panda", name: "Panda", theme: "animals" },
  { id: "koala", name: "Coala", theme: "animals" },
  { id: "kangaroo", name: "Canguru", theme: "animals" },
  { id: "zebra", name: "Zebra", theme: "animals" },
  { id: "hippo", name: "Hipopótamo", theme: "animals" },
  { id: "rhino", name: "Rinoceronte", theme: "animals" },
  { id: "bear", name: "Urso", theme: "animals" },
  { id: "wolf", name: "Lobo", theme: "animals" },
  { id: "fox", name: "Raposa", theme: "animals" },
  { id: "deer", name: "Veado", theme: "animals" },
  { id: "owl", name: "Coruja", theme: "animals" },
  { id: "eagle", name: "Águia", theme: "animals" },
  { id: "parrot", name: "Papagaio", theme: "animals" },
  { id: "snake", name: "Cobra", theme: "animals" },
  { id: "crocodile", name: "Crocodilo", theme: "animals" },
  { id: "turtle", name: "Tartaruga", theme: "animals" },
  { id: "shark", name: "Tubarão", theme: "animals" },
  { id: "whale", name: "Baleia", theme: "animals" },
  { id: "octopus", name: "Polvo", theme: "animals" },
  { id: "seal", name: "Foca", theme: "animals" },
  { id: "penguin", name: "Pinguim", theme: "animals" },
  { id: "cheetah", name: "Guepardo", theme: "animals" },
  { id: "gorilla", name: "Gorila", theme: "animals" },
  { id: "sloth", name: "Preguiça", theme: "animals" },
  { id: "beaver", name: "Castor", theme: "animals" },
  { id: "ostrich", name: "Avestruz", theme: "animals" },
  { id: "camel", name: "Camelo", theme: "animals" },
  { id: "llama", name: "Lhama", theme: "animals" },
  { id: "platypus", name: "Ornitorrinco", theme: "animals" },
  { id: "flamingo", name: "Flamingo", theme: "animals" },
  { id: "meerkat", name: "Suricato", theme: "animals" },
  { id: "raccoon", name: "Guaxinim", theme: "animals" },
  { id: "squirrel", name: "Esquilo", theme: "animals" },
  { id: "hedgehog", name: "Porco-espinho", theme: "animals" },
  { id: "hamster", name: "Hamster", theme: "animals" },
  { id: "chameleon", name: "Camaleão", theme: "animals" },
  { id: "porcupine", name: "Porco-espinho", theme: "animals" },
  { id: "armadillo", name: "Tatu", theme: "animals" },
  { id: "anteater", name: "Tamanduá", theme: "animals" },
  { id: "lemur", name: "Lêmure", theme: "animals" },
  { id: "capybara", name: "Capivara", theme: "animals" },
  { id: "toucan", name: "Tucano", theme: "animals" },
  { id: "peacock", name: "Pavão", theme: "animals" },

  // Personagens
  { id: "mario", name: "Mario", theme: "characters" },
  { id: "spiderman", name: "Homem-Aranha", theme: "characters" },
  { id: "batman", name: "Batman", theme: "characters" },
  { id: "wonderwoman", name: "Mulher Maravilha", theme: "characters" },
  { id: "mickey", name: "Mickey Mouse", theme: "characters" },
  { id: "pikachu", name: "Pikachu", theme: "characters" },
  { id: "sonic", name: "Sonic", theme: "characters" },
  { id: "elsa", name: "Elsa", theme: "characters" },
  { id: "ironman", name: "Homem de Ferro", theme: "characters" },
  { id: "superman", name: "Superman", theme: "characters" },
  { id: "luigi", name: "Luigi", theme: "characters" },
  { id: "thor", name: "Thor", theme: "characters" },
  { id: "hulk", name: "Hulk", theme: "characters" },
  { id: "captainamerica", name: "Capitão América", theme: "characters" },
  { id: "blackwidow", name: "Viúva Negra", theme: "characters" },
  { id: "deadpool", name: "Deadpool", theme: "characters" },
  { id: "wolverine", name: "Wolverine", theme: "characters" },
  { id: "harleyquinn", name: "Arlequina", theme: "characters" },
  { id: "joker", name: "Coringa", theme: "characters" },
  { id: "blackpanther", name: "Pantera Negra", theme: "characters" },
  { id: "doraemon", name: "Doraemon", theme: "characters" },
  { id: "goku", name: "Goku", theme: "characters" },
  { id: "naruto", name: "Naruto", theme: "characters" },
  { id: "spongebob", name: "Bob Esponja", theme: "characters" },
  { id: "bart", name: "Bart Simpson", theme: "characters" },
  { id: "buzz", name: "Buzz Lightyear", theme: "characters" },
  { id: "woody", name: "Woody", theme: "characters" },
  { id: "shrek", name: "Shrek", theme: "characters" },
  { id: "dory", name: "Dory", theme: "characters" },
  { id: "nemo", name: "Nemo", theme: "characters" },
  { id: "minnie", name: "Minnie Mouse", theme: "characters" },
  { id: "donaldduck", name: "Pato Donald", theme: "characters" },
  { id: "goofy", name: "Pateta", theme: "characters" },
  { id: "spongeboby", name: "Bob Esponja", theme: "characters" },
  { id: "patrick", name: "Patrick", theme: "characters" },
  { id: "squidward", name: "Lula Molusco", theme: "characters" },
  { id: "darthvader", name: "Darth Vader", theme: "characters" },
  { id: "yoda", name: "Yoda", theme: "characters" },
  { id: "chewbacca", name: "Chewbacca", theme: "characters" },
  { id: "groot", name: "Groot", theme: "characters" },
  { id: "stitch", name: "Stitch", theme: "characters" },
  { id: "sailor", name: "Sailor Moon", theme: "characters" },
  { id: "aladdin", name: "Aladdin", theme: "characters" },
  { id: "jasmine", name: "Jasmine", theme: "characters" },
  { id: "simba", name: "Simba", theme: "characters" },
  { id: "mulan", name: "Mulan", theme: "characters" },
  { id: "ariel", name: "Ariel", theme: "characters" },
  { id: "belle", name: "Bela", theme: "characters" },
  { id: "cinderella", name: "Cinderela", theme: "characters" },
  { id: "snowwhite", name: "Branca de Neve", theme: "characters" },

  // Filmes
  { id: "titanic", name: "Titanic", theme: "movies" },
  { id: "starwars", name: "Star Wars", theme: "movies" },
  { id: "avatar", name: "Avatar", theme: "movies" },
  { id: "frozen", name: "Frozen", theme: "movies" },
  { id: "matrix", name: "Matrix", theme: "movies" },
  { id: "jurassicpark", name: "Jurassic Park", theme: "movies" },
  { id: "toystory", name: "Toy Story", theme: "movies" },
  { id: "lionking", name: "O Rei Leão", theme: "movies" },
  { id: "harrypotter", name: "Harry Potter", theme: "movies" },
  { id: "avengers", name: "Os Vingadores", theme: "movies" },
  { id: "inception", name: "A Origem", theme: "movies" },
  { id: "gladiator", name: "Gladiador", theme: "movies" },
  { id: "lordoftherings", name: "O Senhor dos Anéis", theme: "movies" },
  { id: "thematrix", name: "Matrix", theme: "movies" },
  { id: "forrestgump", name: "Forrest Gump", theme: "movies" },
  { id: "pulpfiction", name: "Pulp Fiction", theme: "movies" },
  { id: "jaws", name: "Tubarão", theme: "movies" },
  { id: "et", name: "E.T.", theme: "movies" },
  { id: "backfuture", name: "De Volta para o Futuro", theme: "movies" },
  { id: "godfather", name: "O Poderoso Chefão", theme: "movies" },
  { id: "findnemo", name: "Procurando Nemo", theme: "movies" },
  { id: "up", name: "Up: Altas Aventuras", theme: "movies" },
  { id: "coco", name: "Viva: A Vida é uma Festa", theme: "movies" },
  { id: "moana", name: "Moana", theme: "movies" },
  { id: "zootopia", name: "Zootopia", theme: "movies" },
  { id: "insideout", name: "Divertida Mente", theme: "movies" },
  { id: "monsters", name: "Monstros S.A.", theme: "movies" },
  { id: "cars", name: "Carros", theme: "movies" },
  { id: "ratatouille", name: "Ratatouille", theme: "movies" },
  { id: "walle", name: "WALL-E", theme: "movies" },
  { id: "incredibles", name: "Os Incríveis", theme: "movies" },
  { id: "spiderverse", name: "Homem-Aranha no Aranhaverso", theme: "movies" },
  { id: "blackpanther", name: "Pantera Negra", theme: "movies" },
  { id: "wonderwoman", name: "Mulher-Maravilha", theme: "movies" },
  { id: "aquaman", name: "Aquaman", theme: "movies" },
  { id: "deadpool", name: "Deadpool", theme: "movies" },
  { id: "logan", name: "Logan", theme: "movies" },
  { id: "guardians", name: "Guardiões da Galáxia", theme: "movies" },
  { id: "blackwidow", name: "Viúva Negra", theme: "movies" },
  { id: "shangchi", name: "Shang-Chi", theme: "movies" },
  { id: "eternals", name: "Eternos", theme: "movies" },
  { id: "venom", name: "Venom", theme: "movies" },
  { id: "suicidesquad", name: "Esquadrão Suicida", theme: "movies" },
  { id: "batman", name: "Batman", theme: "movies" },
  { id: "joker", name: "Coringa", theme: "movies" },
  { id: "superman", name: "Superman", theme: "movies" },
  { id: "wonderwoman", name: "Mulher-Maravilha", theme: "movies" },
  { id: "justiceleague", name: "Liga da Justiça", theme: "movies" },
  { id: "captainmarvel", name: "Capitã Marvel", theme: "movies" },
  { id: "blackpanther", name: "Pantera Negra", theme: "movies" },

  // Locais
  { id: "paris", name: "Paris", theme: "places" },
  { id: "nyc", name: "Nova York", theme: "places" },
  { id: "rio", name: "Rio de Janeiro", theme: "places" },
  { id: "tokyo", name: "Tóquio", theme: "places" },
  { id: "venice", name: "Veneza", theme: "places" },
  { id: "pyramids", name: "Pirâmides do Egito", theme: "places" },
  { id: "tajmahal", name: "Taj Mahal", theme: "places" },
  { id: "london", name: "Londres", theme: "places" },
  { id: "rome", name: "Roma", theme: "places" },
  { id: "greatwall", name: "Muralha da China", theme: "places" },
  { id: "sydney", name: "Sydney", theme: "places" },
  { id: "machu", name: "Machu Picchu", theme: "places" },
  { id: "petra", name: "Petra", theme: "places" },
  { id: "santorini", name: "Santorini", theme: "places" },
  { id: "dubai", name: "Dubai", theme: "places" },
  { id: "moscow", name: "Moscou", theme: "places" },
  { id: "barcelona", name: "Barcelona", theme: "places" },
  { id: "amsterdam", name: "Amsterdã", theme: "places" },
  { id: "athens", name: "Atenas", theme: "places" },
  { id: "istanbul", name: "Istambul", theme: "places" },
  { id: "bali", name: "Bali", theme: "places" },
  { id: "hawaii", name: "Havaí", theme: "places" },
  { id: "maldives", name: "Maldivas", theme: "places" },
  { id: "cancun", name: "Cancún", theme: "places" },
  { id: "vatican", name: "Vaticano", theme: "places" },
  { id: "giza", name: "Giza", theme: "places" },
  { id: "stonehenge", name: "Stonehenge", theme: "places" },
  { id: "kremlin", name: "Kremlin", theme: "places" },
  { id: "louvre", name: "Museu do Louvre", theme: "places" },
  { id: "colosseum", name: "Coliseu", theme: "places" },
  { id: "eiffel", name: "Torre Eiffel", theme: "places" },
  { id: "bigben", name: "Big Ben", theme: "places" },
  { id: "christredeemer", name: "Cristo Redentor", theme: "places" },
  { id: "statueofliberty", name: "Estátua da Liberdade", theme: "places" },
  { id: "manhattan", name: "Manhattan", theme: "places" },
  { id: "hollywood", name: "Hollywood", theme: "places" },
  { id: "lasvegas", name: "Las Vegas", theme: "places" },
  { id: "copacabana", name: "Copacabana", theme: "places" },
  { id: "ipanema", name: "Ipanema", theme: "places" },
  { id: "amazon", name: "Floresta Amazônica", theme: "places" },
  { id: "iguazu", name: "Cataratas do Iguaçu", theme: "places" },
  { id: "sahara", name: "Deserto do Saara", theme: "places" },
  { id: "everest", name: "Monte Everest", theme: "places" },
  { id: "grandcanyon", name: "Grand Canyon", theme: "places" },
  { id: "niagara", name: "Cataratas do Niágara", theme: "places" },
  { id: "yellowstone", name: "Yellowstone", theme: "places" },
  { id: "galapagos", name: "Ilhas Galápagos", theme: "places" },
  { id: "kilimanjaro", name: "Monte Kilimanjaro", theme: "places" },
  { id: "antarcticabase", name: "Base Antártica", theme: "places" },
  { id: "northpole", name: "Polo Norte", theme: "places" },

  // Objetos
  { id: "phone", name: "Telefone", theme: "objects" },
  { id: "chair", name: "Cadeira", theme: "objects" },
  { id: "tv", name: "Televisão", theme: "objects" },
  { id: "book", name: "Livro", theme: "objects" },
  { id: "car", name: "Carro", theme: "objects" },
  { id: "computer", name: "Computador", theme: "objects" },
  { id: "watch", name: "Relógio", theme: "objects" },
  { id: "guitar", name: "Violão", theme: "objects" },
  { id: "camera", name: "Câmera", theme: "objects" },
  { id: "umbrella", name: "Guarda-chuva", theme: "objects" },
  { id: "pencil", name: "Lápis", theme: "objects" },
  { id: "pen", name: "Caneta", theme: "objects" },
  { id: "notebook", name: "Caderno", theme: "objects" },
  { id: "scissors", name: "Tesoura", theme: "objects" },
  { id: "backpack", name: "Mochila", theme: "objects" },
  { id: "wallet", name: "Carteira", theme: "objects" },
  { id: "keys", name: "Chaves", theme: "objects" },
  { id: "sunglasses", name: "Óculos de Sol", theme: "objects" },
  { id: "headphones", name: "Fones de Ouvido", theme: "objects" },
  { id: "microphone", name: "Microfone", theme: "objects" },
  { id: "lamp", name: "Lâmpada", theme: "objects" },
  { id: "mirror", name: "Espelho", theme: "objects" },
  { id: "toothbrush", name: "Escova de Dentes", theme: "objects" },
  { id: "soap", name: "Sabonete", theme: "objects" },
  { id: "towel", name: "Toalha", theme: "objects" },
  { id: "pillow", name: "Travesseiro", theme: "objects" },
  { id: "blanket", name: "Cobertor", theme: "objects" },
  { id: "fan", name: "Ventilador", theme: "objects" },
  { id: "airconditioner", name: "Ar Condicionado", theme: "objects" },
  { id: "refrigerator", name: "Geladeira", theme: "objects" },
  { id: "microwave", name: "Micro-ondas", theme: "objects" },
  { id: "oven", name: "Forno", theme: "objects" },
  { id: "dishwasher", name: "Lava-louças", theme: "objects" },
  { id: "washingmachine", name: "Máquina de Lavar", theme: "objects" },
  { id: "vacuum", name: "Aspirador de Pó", theme: "objects" },
  { id: "iron", name: "Ferro de Passar", theme: "objects" },
  { id: "broom", name: "Vassoura", theme: "objects" },
  { id: "mop", name: "Rodo", theme: "objects" },
  { id: "bucket", name: "Balde", theme: "objects" },
  { id: "trashcan", name: "Lixeira", theme: "objects" },
  { id: "doorbell", name: "Campainha", theme: "objects" },
  { id: "lock", name: "Cadeado", theme: "objects" },
  { id: "doorknob", name: "Maçaneta", theme: "objects" },
  { id: "window", name: "Janela", theme: "objects" },
  { id: "curtain", name: "Cortina", theme: "objects" },
  { id: "blinds", name: "Persiana", theme: "objects" },
  { id: "carpet", name: "Tapete", theme: "objects" },
  { id: "vase", name: "Vaso", theme: "objects" },
  { id: "painting", name: "Quadro", theme: "objects" },
  { id: "clock", name: "Relógio de Parede", theme: "objects" },

  // Famosos
  { id: "neymar", name: "Neymar", theme: "famous" },
  { id: "madonna", name: "Madonna", theme: "famous" },
  { id: "einstein", name: "Einstein", theme: "famous" },
  { id: "michaeljackson", name: "Michael Jackson", theme: "famous" },
  { id: "shakespeare", name: "Shakespeare", theme: "famous" },
  { id: "chaplin", name: "Charlie Chaplin", theme: "famous" },
  { id: "beethoven", name: "Beethoven", theme: "famous" },
  { id: "picasso", name: "Picasso", theme: "famous" },
  { id: "elvis", name: "Elvis Presley", theme: "famous" },
  { id: "mandela", name: "Nelson Mandela", theme: "famous" },
  { id: "messi", name: "Lionel Messi", theme: "famous" },
  { id: "ronaldo", name: "Cristiano Ronaldo", theme: "famous" },
  { id: "pele", name: "Pelé", theme: "famous" },
  { id: "maradona", name: "Maradona", theme: "famous" },
  { id: "obama", name: "Barack Obama", theme: "famous" },
  { id: "trump", name: "Donald Trump", theme: "famous" },
  { id: "queen", name: "Rainha Elizabeth", theme: "famous" },
  { id: "pope", name: "Papa Francisco", theme: "famous" },
  { id: "davinci", name: "Leonardo da Vinci", theme: "famous" },
  { id: "gandhi", name: "Mahatma Gandhi", theme: "famous" },
  { id: "freud", name: "Sigmund Freud", theme: "famous" },
  { id: "newton", name: "Isaac Newton", theme: "famous" },
  { id: "darwin", name: "Charles Darwin", theme: "famous" },
  { id: "tesla", name: "Nikola Tesla", theme: "famous" },
  { id: "hawking", name: "Stephen Hawking", theme: "famous" },
  { id: "mozart", name: "Wolfgang Mozart", theme: "famous" },
  { id: "davinci", name: "Leonardo da Vinci", theme: "famous" },
  { id: "vancough", name: "Vincent van Gogh", theme: "famous" },
  { id: "dali", name: "Salvador Dalí", theme: "famous" },
  { id: "frida", name: "Frida Kahlo", theme: "famous" },
  { id: "chaplin", name: "Charlie Chaplin", theme: "famous" },
  { id: "marilyn", name: "Marilyn Monroe", theme: "famous" },
  { id: "audrey", name: "Audrey Hepburn", theme: "famous" },
  { id: "elvis", name: "Elvis Presley", theme: "famous" },
  { id: "beatles", name: "The Beatles", theme: "famous" },
  { id: "queen", name: "Queen", theme: "famous" },
  { id: "madonna", name: "Madonna", theme: "famous" },
  { id: "michaeljackson", name: "Michael Jackson", theme: "famous" },
  { id: "prince", name: "Prince", theme: "famous" },
  { id: "beyonce", name: "Beyoncé", theme: "famous" },
  { id: "ladygaga", name: "Lady Gaga", theme: "famous" },
  { id: "adele", name: "Adele", theme: "famous" },
  { id: "taylorswift", name: "Taylor Swift", theme: "famous" },
  { id: "drake", name: "Drake", theme: "famous" },
  { id: "eminem", name: "Eminem", theme: "famous" },
  { id: "snoopdogg", name: "Snoop Dogg", theme: "famous" },
  { id: "kanyewest", name: "Kanye West", theme: "famous" },
  { id: "rihanna", name: "Rihanna", theme: "famous" },
  { id: "shakira", name: "Shakira", theme: "famous" },
  { id: "jlo", name: "Jennifer Lopez", theme: "famous" }
];

export function getItemsByTheme(themeId: ThemeId): GuessItem[] {
  return shuffle(items.filter(item => item.theme === themeId));
}