name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
  # Permite execução manual do workflow
  workflow_dispatch:
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Installing Firebase CLI..."
          npm install -g firebase-tools
        
      # Pulando etapa de linting já que não temos script de lint no package.json
      - name: Skip Linting
        run: echo "Linting skipped - no lint script in package.json"
        
      - name: Build
        run: |
          echo "Iniciando o processo de build..."
          npm run build
          echo "Verificando conteúdo da pasta dist após o build..."
          ls -la dist/
          echo "Verificando conteúdo da pasta dist/public (destino do Firebase)..."
          ls -la dist/public/ || echo "Pasta dist/public não existe"
        env:
          # Adicionando variáveis de ambiente necessárias para o build
          NODE_ENV: production
          
      - name: Preparar pasta para deploy
        run: |
          echo "Verificando e criando a pasta dist/public se necessário..."
          mkdir -p dist/public
          # Se a pasta dist/public estiver vazia, copiamos o conteúdo de dist/client para ela
          if [ ! "$(ls -A dist/public 2>/dev/null)" ]; then
            echo "dist/public está vazia ou não existe, verificando outras pastas..."
            if [ -d "dist/client" ]; then
              echo "Copiando conteúdo de dist/client para dist/public..."
              cp -r dist/client/* dist/public/
            fi
          fi
          echo "Conteúdo final da pasta dist/public:"
          ls -la dist/public || echo "Pasta dist/public ainda não existe ou está vazia"
      
      - name: Deploy to Firebase
        run: |
          echo "Verificando versão do Node.js..."
          node --version
          echo "Verificando versão do NPM..."
          npm --version
          echo "Verificando a configuração do Firebase..."
          npx firebase --version
          echo "Verificando o arquivo firebase.json..."
          cat firebase.json
          echo "Verificando o arquivo .firebaserc..."
          cat .firebaserc
          echo "Deploying to Firebase using token..."
          # Verificar se o token está definido
          if [ -z "$FIREBASE_TOKEN" ]; then
            echo "ERRO: Token do Firebase não encontrado"
            exit 1
          fi
          
          # Determinar a versão correta do Firebase CLI com base na versão do Node.js
          NODE_VERSION=$(node -v | cut -d 'v' -f2)
          NODE_MAJOR_VERSION=$(echo $NODE_VERSION | cut -d '.' -f1)
          
          if [ $NODE_MAJOR_VERSION -lt 20 ]; then
            echo "Usando Firebase CLI v11.30.0 compatível com Node.js $NODE_VERSION"
            npm install firebase-tools@11.30.0 --no-save
            npx firebase@11.30.0 deploy --only hosting --token "$FIREBASE_TOKEN" --non-interactive --debug
          else
            echo "Usando Firebase CLI versão mais recente"
            npx firebase deploy --only hosting --token "$FIREBASE_TOKEN" --non-interactive --debug
          fi
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CI: true
          
      - name: Notify Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deploy concluído com sucesso!"
            echo "Seu app está disponível em:"
            echo "https://gorf-jogo-de-bebidas.web.app"
            echo "https://gorf.com.br"
          else
            echo "❌ Falha no deploy. Verifique os logs acima para mais detalhes."
          fi